[package]
name = "markov-bot"
version = "0.1.1"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
serenity = { git = "https://github.com/serenity-rs/serenity", features = [
    "collector",
] }
sqlx = { version = "0.8", features = [
    "runtime-tokio-rustls",
    "sqlite",
    "chrono",
    "uuid",
] }
rand = "0.8.5"
tokio = { version = "1.38", features = ["macros", "rt-multi-thread"] }
futures = "0.3.31"
