# Put your profiles here

[[users]]
username = "midekai"
avatar_link = "https://yorunoken.s-ul.eu/DxxEGuRp"

[[users]]
username = "sun"
avatar_link = "https://yorunoken.s-ul.eu/5bHOYXPN"

[[users]]
username = "riya"
avatar_link = "https://yorunoken.s-ul.eu/u5KsMJQi"

[[users]]
username = "akari"
avatar_link = "https://yorunoken.s-ul.eu/juMKMH3d"

[[users]]
username = "night"
avatar_link = "https://yorunoken.s-ul.eu/H17pVOjv"

[[users]]
username = "ayumi"
avatar_link = "https://yorunoken.s-ul.eu/WZoeehpH"
