# Put your profiles here

avatar_links = [
    "https://yorunoken.s-ul.eu/DxxEGuRp",
    "https://yorunoken.s-ul.eu/5bHOYXPN",
    "https://yorunoken.s-ul.eu/u5KsMJQi",
    "https://yorunoken.s-ul.eu/juMKMH3d",
    "https://yorunoken.s-ul.eu/H17pVOjv",
    "https://yorunoken.s-ul.eu/WZoeehpH",
]
