name: Linux build for x86

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Build binary
              run: cargo build -r --verbose

            - name: Run tests
              run: cargo test --verbose

            - name: Upload build artifact
              uses: actions/upload-artifact@v4
              with:
                  name: markov-bot_x86_64
                  path: target/release/markov-bot
